import 'package:my_demo/core/constants/app_images.dart';
import 'package:my_demo/core/localization/localization.dart';
import 'package:get/get.dart';
import 'package:my_demo/model/models/meal_detials_class.dart';

final String mealTypeBeef = AppLocal.beef.tr;
final String mealTypeChin = AppLocal.chin.tr;
final String mealTypejuice = AppLocal.juice.tr;
final String mealTypeNoodles = AppLocal.noodles.tr;
final String mealTypePasta = AppLocal.pasta.tr;
final String mealTypeSalad = AppLocal.salad.tr;
final String mealTypeSoda = AppLocal.soda.tr;

///
///

final List<MealDetailsClass> beefDetailsData = [
  MealDetailsClass(
      mealTitle: mealTypeBeef,
      mealPrefDiscription: AppLocal.beefPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeBeef,
      mealImg: FoodImages.beef1,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeBeef,
      mealPrefDiscription: AppLocal.beefPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeBeef,
      mealImg: FoodImages.beef2,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeBeef,
      mealPrefDiscription: AppLocal.beefPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeBeef,
      mealImg: FoodImages.beef3,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeBeef,
      mealPrefDiscription: AppLocal.beefPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeBeef,
      mealImg: FoodImages.beef4,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeBeef,
      mealPrefDiscription: AppLocal.beefPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeBeef,
      mealImg: FoodImages.beef5,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
];

///
///
///

final List<MealDetailsClass> chineseDetialsData = [
  MealDetailsClass(
      mealTitle: mealTypeChin,
      mealPrefDiscription: AppLocal.chinPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeChin,
      mealImg: FoodImages.chin1,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeChin,
      mealPrefDiscription: AppLocal.chinPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeChin,
      mealImg: FoodImages.chin2,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeChin,
      mealPrefDiscription: AppLocal.chinPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeChin,
      mealImg: FoodImages.chin3,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeChin,
      mealPrefDiscription: AppLocal.chinPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeChin,
      mealImg: FoodImages.chin4,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeChin,
      mealPrefDiscription: AppLocal.chinPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeChin,
      mealImg: FoodImages.chin5,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeChin,
      mealPrefDiscription: AppLocal.chinPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeChin,
      mealImg: FoodImages.chin6,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeChin,
      mealPrefDiscription: AppLocal.chinPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeChin,
      mealImg: FoodImages.chin7,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeChin,
      mealPrefDiscription: AppLocal.chinPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeChin,
      mealImg: FoodImages.chin8,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeChin,
      mealPrefDiscription: AppLocal.chinPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeChin,
      mealImg: FoodImages.chin9,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeChin,
      mealPrefDiscription: AppLocal.chinPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeChin,
      mealImg: FoodImages.chin10,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeChin,
      mealPrefDiscription: AppLocal.chinPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeChin,
      mealImg: FoodImages.chin11,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeChin,
      mealPrefDiscription: AppLocal.chinPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeChin,
      mealImg: FoodImages.chin12,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeChin,
      mealPrefDiscription: AppLocal.chinPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeChin,
      mealImg: FoodImages.chin1,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeChin,
      mealPrefDiscription: AppLocal.chinPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeChin,
      mealImg: FoodImages.chin2,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeChin,
      mealPrefDiscription: AppLocal.chinPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeChin,
      mealImg: FoodImages.chin3,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
];

///
///
///

final List<MealDetailsClass> juiceDetialsData = [
  MealDetailsClass(
      mealTitle: mealTypejuice,
      mealPrefDiscription: AppLocal.juicePrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypejuice,
      mealImg: FoodImages.juice1,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypejuice,
      mealPrefDiscription: AppLocal.juicePrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypejuice,
      mealImg: FoodImages.juice2,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypejuice,
      mealPrefDiscription: AppLocal.juicePrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypejuice,
      mealImg: FoodImages.juice3,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypejuice,
      mealPrefDiscription: AppLocal.juicePrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypejuice,
      mealImg: FoodImages.juice4,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypejuice,
      mealPrefDiscription: AppLocal.juicePrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypejuice,
      mealImg: FoodImages.juice5,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypejuice,
      mealPrefDiscription: AppLocal.juicePrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypejuice,
      mealImg: FoodImages.juice6,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypejuice,
      mealPrefDiscription: AppLocal.juicePrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypejuice,
      mealImg: FoodImages.juice7,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypejuice,
      mealPrefDiscription: AppLocal.juicePrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypejuice,
      mealImg: FoodImages.juice8,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypejuice,
      mealPrefDiscription: AppLocal.juicePrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypejuice,
      mealImg: FoodImages.juice9,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypejuice,
      mealPrefDiscription: AppLocal.juicePrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypejuice,
      mealImg: FoodImages.juice10,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypejuice,
      mealPrefDiscription: AppLocal.juicePrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypejuice,
      mealImg: FoodImages.juice11,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypejuice,
      mealPrefDiscription: AppLocal.juicePrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypejuice,
      mealImg: FoodImages.juice12,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypejuice,
      mealPrefDiscription: AppLocal.juicePrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypejuice,
      mealImg: FoodImages.juice13,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypejuice,
      mealPrefDiscription: AppLocal.juicePrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypejuice,
      mealImg: FoodImages.juice14,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypejuice,
      mealPrefDiscription: AppLocal.juicePrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypejuice,
      mealImg: FoodImages.juice15,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypejuice,
      mealPrefDiscription: AppLocal.juicePrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypejuice,
      mealImg: FoodImages.juice16,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypejuice,
      mealPrefDiscription: AppLocal.juicePrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypejuice,
      mealImg: FoodImages.juice17,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
];

///
///
///

final List<MealDetailsClass> noodlesDetialsData = [
  MealDetailsClass(
      mealTitle: mealTypeNoodles,
      mealPrefDiscription: AppLocal.noodlesPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeNoodles,
      mealImg: FoodImages.noodles1,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeNoodles,
      mealPrefDiscription: AppLocal.noodlesPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeNoodles,
      mealImg: FoodImages.noodles2,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeNoodles,
      mealPrefDiscription: AppLocal.noodlesPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeNoodles,
      mealImg: FoodImages.noodles3,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeNoodles,
      mealPrefDiscription: AppLocal.noodlesPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeNoodles,
      mealImg: FoodImages.noodles4,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeNoodles,
      mealPrefDiscription: AppLocal.noodlesPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeNoodles,
      mealImg: FoodImages.noodles5,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeNoodles,
      mealPrefDiscription: AppLocal.noodlesPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeNoodles,
      mealImg: FoodImages.noodles6,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeNoodles,
      mealPrefDiscription: AppLocal.noodlesPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeNoodles,
      mealImg: FoodImages.noodles7,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeNoodles,
      mealPrefDiscription: AppLocal.noodlesPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeNoodles,
      mealImg: FoodImages.noodles8,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
];

///
///
///

final List<MealDetailsClass> pastaDetialsData = [
  MealDetailsClass(
      mealTitle: mealTypePasta,
      mealPrefDiscription: AppLocal.pastaPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypePasta,
      mealImg: FoodImages.pasta1,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypePasta,
      mealPrefDiscription: AppLocal.pastaPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypePasta,
      mealImg: FoodImages.pasta2,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypePasta,
      mealPrefDiscription: AppLocal.pastaPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypePasta,
      mealImg: FoodImages.pasta3,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypePasta,
      mealPrefDiscription: AppLocal.pastaPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypePasta,
      mealImg: FoodImages.pasta4,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypePasta,
      mealPrefDiscription: AppLocal.pastaPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypePasta,
      mealImg: FoodImages.pasta5,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypePasta,
      mealPrefDiscription: AppLocal.pastaPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypePasta,
      mealImg: FoodImages.pasta6,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypePasta,
      mealPrefDiscription: AppLocal.pastaPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypePasta,
      mealImg: FoodImages.pasta9,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypePasta,
      mealPrefDiscription: AppLocal.pastaPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypePasta,
      mealImg: FoodImages.pasta10,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
];

///
///
///

final List<MealDetailsClass> saladDetialsData = [
  MealDetailsClass(
      mealTitle: mealTypeSalad,
      mealPrefDiscription: AppLocal.saladPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeSalad,
      mealImg: FoodImages.salad1,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeSalad,
      mealPrefDiscription: AppLocal.saladPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeSalad,
      mealImg: FoodImages.salad2,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeSalad,
      mealPrefDiscription: AppLocal.saladPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeSalad,
      mealImg: FoodImages.salad3,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeSalad,
      mealPrefDiscription: AppLocal.saladPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeSalad,
      mealImg: FoodImages.salad4,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeSalad,
      mealPrefDiscription: AppLocal.saladPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeSalad,
      mealImg: FoodImages.salad1,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeSalad,
      mealPrefDiscription: AppLocal.saladPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeSalad,
      mealImg: FoodImages.salad2,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeSalad,
      mealPrefDiscription: AppLocal.saladPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeSalad,
      mealImg: FoodImages.salad3,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeSalad,
      mealPrefDiscription: AppLocal.saladPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeSalad,
      mealImg: FoodImages.salad4,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
];

///
///
///

final List<MealDetailsClass> sodaDetialsData = [
  MealDetailsClass(
      mealTitle: mealTypeSoda,
      mealPrefDiscription: AppLocal.sodaPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeSoda,
      mealImg: FoodImages.juice1,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeSoda,
      mealPrefDiscription: AppLocal.sodaPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeSoda,
      mealImg: FoodImages.juice2,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeSoda,
      mealPrefDiscription: AppLocal.sodaPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeSoda,
      mealImg: FoodImages.juice3,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeSoda,
      mealPrefDiscription: AppLocal.sodaPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeSoda,
      mealImg: FoodImages.juice4,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeSoda,
      mealPrefDiscription: AppLocal.sodaPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeSoda,
      mealImg: FoodImages.juice5,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeSoda,
      mealPrefDiscription: AppLocal.sodaPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeSoda,
      mealImg: FoodImages.juice1,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeSoda,
      mealPrefDiscription: AppLocal.sodaPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeSoda,
      mealImg: FoodImages.juice3,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeSoda,
      mealPrefDiscription: AppLocal.sodaPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeSoda,
      mealImg: FoodImages.juice4,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeSoda,
      mealPrefDiscription: AppLocal.sodaPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeSoda,
      mealImg: FoodImages.juice3,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
  MealDetailsClass(
      mealTitle: mealTypeSoda,
      mealPrefDiscription: AppLocal.sodaPrefDiscrip.tr,
      mealDiscription: AppLocal.macdonalz.tr,
      mealType: mealTypeSoda,
      mealImg: FoodImages.juice4,
      mealPrice: 2,
      mealCount: 2,
      mealRating: 2,
      mealStarsCount: 2),
];
